on: [push]

jobs:
  retrieve_version_job:
    runs-on: ubuntu-latest
    name: retrieve branch version
    steps:
    - uses: actions/checkout@v3
    - id: version-retriever
      uses: ./../action.yml
    - name: echo retrieved version
      run: echo retrieved version => ${{ steps.version-retriever.outputs.version }}
      shell: bash
